hashicorp/consul-ui-toolkit

- CONTRIBUTING.md
- package.json
- toolkit/package.json
A description of how we can use [Yalc](https://github.com/wclr/yalc) can be found in the [RFC](https://go.hashi.co/rfc/csl-3822). There isn’t a ton to “add to the repo” except a script for publishing the local build to yalc, and a script for cleanup if it seems like it would be helpful. It would also be good to include documentation on how to use yalc with the toolkit.
**AC**
Add script for publishing builds with yalc (optionally one for cleanup as well)
Add documentation on how to use yalc with the toolkit
[RFC](https://go.hashi.co/rfc/csl-3822)
[Yalc](https://github.com/wclr/yalc)
https://hashicorp.atlassian.net/browse/CC-4211
- cd toolkit 
- yarn toolkit:publish
- yarn toolkit:cleanup
- :moyai: **[boulder]**: …
> add yalc setup to scripts

- package.json
The [release action has been failing](https://github.com/hashicorp/consul-ui-toolkit/actions/runs/4994640794/jobs/8945486986). There is an error mentioning that there are no changes after the version script is ran. Looks like I needed to add a yarn script for calling the changesets version command. At least that's what I think needed to happen :). Based this on the [design-system package.json scripts](https://github.com/hashicorp/design-system/blob/5012cd96f609b4951927bf5568bdb461305481dd/package.json#L15) and ran it locally to see that there would indeed be changes to commit.
[CC-5064](https://hashicorp.atlassian.net/browse/CC-5064)
- :white_circle: **[pebble]**: Non-blocking, but …
> CC-5064: add changesets version script

- .changeset/short-moose-turn.md
- .github/workflows/ci.yml
- documentation/app/components/component-api/index.hbs
- documentation/app/styles/app.scss
- documentation/app/styles/components/component-api.scss
- documentation/app/templates/components/list-item.hbs
- documentation/package.json
- documentation/tests/integration/components/component-api-test.js
- toolkit/package.json
- yarn.lock
I started working on the code section for the list item docs decided to split this component out into it's own PR. It's based off the [design system docs](https://helios.hashicorp.design/components/badge?tab=code#component-api) but not trying to be an exact clone (re: text size & colors). We don't have the blue available in the badges so I'm curious what color you prefer? I think neutral is fine.
Here are the badges in highlight colors
Here are the badges in neutral colors
- :sparkles: **[dust]**: Non-blocking. "Take it or …
> Add component api docs component

- .changeset/odd-fishes-smoke.md
- documentation/tests/integration/components/list-item-test.js
- toolkit/src/components/cut/list-item/index.hbs
- toolkit/src/styles/components/list-item.scss
**Note: floating deps are failing but are addressed in #26. I won't be merging this until #26 gets in.**
- Updates the `<Cut::ListItem />` to use a `li` for it's containing element
- Update the `<Cut::ListItem />` to have a `surface-primary` background-color by default so that it's not transparent. ([see docs](https://www.figma.com/file/SenC8kTQNUJKCvOvcL8WPu/Consul-Component-Library?type=design&node-id=640-83276&t=7NjWWYHm7kEvePlA-0))
**Before:**
**After:**
You may also see the [latest of the in-progress docs](https://consul-ui-toolkit-documentation-6ghtntzm9-hashicorp.vercel.app/components/list-item) that has these commits as well.
- :white_circle: **[pebble]**: Non-blocking, but …
> Update list-item element and background-color

- .changeset/healthy-otters-repair.md
- documentation/app/components/list-item/index.hbs
- documentation/package.json
- toolkit/package.json
- yarn.lock
- Upgrade @hashicorp/design-system-components to 2.7.0
- Remove dependency on design-system-tokens as we get it implicitly through design-system-components. We should only have to install it directly if we aren't using the component library.
Styles still work
> Upgrade @hashicorp/design-system-components to 2.7.0

- .changeset/chilled-experts-taste.md
- documentation/app/components/component-api/index.hbs
- documentation/app/controllers/components/service-instance-list-item.js
- documentation/app/router.js
- documentation/app/styles/components/component-api.scss
- documentation/app/templates/application.hbs
- documentation/app/templates/components/service-instance-list-item.hbs
- toolkit/src/components/cut/list-item/service-instance/index.ts
Add service instance list item docs, very similar to service list item docs. Realized that it may be good to switch the name of the `service` arg to `instance` but not part of this PR.
- [CC-5328](https://hashicorp.atlassian.net/browse/CC-5328)
[CC-5328]: https://hashicorp.atlassian.net/browse/CC-5328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CC-5328: add service-instance list item docs

- LICENSE
Hey folks! 👋 
[Copywrite](https://github.com/hashicorp/copywrite) audits happened to be erroring out for this repo. Upon further investigation, it looks like the first few sentences of the MPL-2.0 license text were inadvertently missing, so this PR adds them back in.
You can regenerate the contents of this PR by removing the `LICENSE` file and running Copywrite locally:
```
copywrite license --spdx MPL-2.0
```
Cheers!
> Fix missing MPL-2.0 license text

- .changeset/selfish-poets-share.md
- toolkit/package.json
- toolkit/src/components/cut/copy-block/index.ts
- toolkit/src/components/cut/copy-block/types.ts
- toolkit/src/components/cut/filter-bar/filter/checkbox.ts
- toolkit/src/components/cut/filter-bar/filter/checkmark.ts
- toolkit/src/components/cut/filter-bar/filter/index.ts
- toolkit/src/components/cut/filter-bar/filter/radio.ts
- toolkit/src/components/cut/filter-bar/index.ts
- toolkit/src/components/cut/filter-bar/sort/checkmark.ts
- toolkit/src/components/cut/filter-bar/types.ts
- toolkit/src/components/cut/list-item/index.ts
- toolkit/src/components/cut/list-item/service-instance/index.ts
- toolkit/src/components/cut/list-item/service/index.ts
- toolkit/src/components/cut/list-item/types.ts
- toolkit/src/components/cut/list/pagination.ts
- toolkit/src/components/cut/list/types.ts
- toolkit/src/components/cut/metadata/external-source/index.ts
- toolkit/src/components/cut/metadata/health-check-badge-set/index.ts
- toolkit/src/components/cut/metadata/types.ts
- toolkit/src/components/cut/text-with-icon/index.ts
- toolkit/src/components/cut/text-with-icon/types.ts
- toolkit/src/index.ts
- toolkit/src/types/index.ts
- toolkit/src/utils/index.ts
- toolkit/src/utils/service-list-item.ts
I was working on building the services list ui cloud-ui and I found that I had to import constants and types from the actual dist folder and the path to where the export was happening. I didn't like how that made me feel so I did some work to change that. Now if you want any types to be exported from the root package you can export them from the `types/index.ts` file. Similarly you can also export any utility constants/functions from `utils/index.ts` to also be able to import them straight from `@hashicorp/consul-ui-toolkit`.
I made this a major change as it breaks where types were located. It really doesn't matter yet as the previous version hadn't been used except in my wip PR but there is not harm in versioning.
**Before:**
**After:** …
> CC-6167: Export all types from an index file

- .changeset/nasty-shoes-repair.md
- toolkit/src/components/cut/list/pagination.ts
Updates the paginaton page size default handler to always specify the route name when transitioning
Updates the pagination routing query function to set separate query parameters for next or previous page.
Grouping this breaking change with the other current major change that is pending release.
https://github.com/hashicorp/consul-ui-toolkit/assets/5448834/e574bad9-a362-4e0c-a267-5a2828c7e7cc
[CC-5556](https://hashicorp.atlassian.net/browse/CC-5556)
[CC-5556]: …
> CC-5556: Update list pagination routing behaviour

- .changeset/healthy-lamps-hammer.md
- toolkit/src/components/cut/list-item/index.hbs
- toolkit/src/components/cut/list-item/service-instance/index.hbs
- toolkit/src/components/cut/list-item/service/index.hbs
- toolkit/src/components/cut/list-item/types.ts
Pass through the model and models to the underlying `Hds::Interactive` component in `Cut::ListItem`, `Cut::ListItem::Service` and `Cut::ListItem::ServiceInstance`
https://github.com/hashicorp/consul-ui-toolkit/assets/5448834/bb0f0c30-3b31-4d86-9c65-912b4e50d649
> CC-5556: list-item - pass models/model through to HDS::Interactive

- .changeset/ten-pianos-drum.md
- documentation/app/templates/components/filter-bar.hbs
- documentation/tests/integration/components/filter-bar-test.js
- toolkit/src/components/cut/filter-bar/index.hbs
- toolkit/src/components/cut/filter-bar/index.ts
- toolkit/src/components/cut/filter-bar/types.ts
Adds the `@name` argument to `Cut::FilterBar` and updates the default text to show generic result text that doesn't reference the number of returned items.
> CC-5556: update filter bar results text

- .changeset/selfish-mice-shout.md
- documentation/tests/integration/components/filter-bar-test.js
- toolkit/src/components/cut/filter-bar/index.hbs
- toolkit/src/components/cut/filter-bar/index.ts
Updates the FilterBar results text to be "Filters applied:" when no count is passed in and you have used at least one filter
[CC-6116](https://hashicorp.atlassian.net/browse/CC-6116)
[CC-6116]: https://hashicorp.atlassian.net/browse/CC-6116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CC-6116: filter bar results text

- .changeset/beige-clouds-work.md
- CONTRIBUTING.md
- documentation/tests/integration/components/service-list-item-test.js
- documentation/tests/pages/service-list-item.js
- toolkit/package.json
- toolkit/src/components/cut/list-item/service/index.hbs
- toolkit/src/components/cut/list-item/service/index.ts
- toolkit/src/components/cut/metadata/health-check-badge-set/index.hbs
- toolkit/src/components/cut/metadata/service-health-badge/index.hbs
- toolkit/src/components/cut/metadata/service-health-badge/index.ts
- toolkit/src/components/cut/metadata/types.ts
Acceptance Criteria
- If there is more than one critical check, show critical status with a tooltip
- If there is more than one warning, and no critical checks, show warning status with a tooltip
- If there is only passing checks, show healthy status with a tooltip
old design:
new design:
Note: these tooltips do actually pop up downwards like this, but when the `ListItem` is in a `PreviewBlock`, there's not enough space so I guess it pops upwards 🤷 
[jira](https://hashicorp.atlassian.net/browse/CC-6223)
- :sparkles: …
> CC-6223: Update how statuses are displayed on Cut::ListItem::Service

- .changeset/olive-ducks-fold.md
- documentation/tests/integration/components/filter-bar-test.js
- toolkit/src/components/cut/filter-bar/index.hbs
- toolkit/src/components/cut/filter-bar/search.hbs
Updates `<Cut::FilterBar::Search />` to use the search value from the filter bar config to populate it's input value. This makes it so that if the search value is read in by the config (for example via query parameters) the search value will update accordingly.
https://github.com/hashicorp/consul-ui-toolkit/assets/5448834/489da486-9066-4712-aebe-6e8235e58ffb
https://github.com/hashicorp/cloud-ui/pull/7382
> Update  FIlterBar Search to use config search value

- .changeset/thirty-ants-tie.md
- documentation/app/controllers/components/service-list-item.js
- documentation/app/templates/components/service-list-item.hbs
- documentation/tests/integration/components/service-list-item-test.js
- toolkit/src/components/cut/list-item/service/index.hbs
- toolkit/src/components/cut/list-item/service/index.ts
- toolkit/src/components/cut/list-item/types.ts
Updates `SERVICE_KIND` to include all the service types and updates showing the kind to be based on if the `kindName` is found. Functionally, this doesn't change anything, but now we can just always pass in the service kind that is returned from the API instead of altering it in the consuming app.
Reference API PR: https://github.com/hashicorp/cloud-global-network-manager-service/pull/987
https://github.com/hashicorp/cloud-global-network-manager-service/pull/987
> Update SERVICE_KIND to include all service kinds

- .changeset/tall-windows-allow.md
- documentation/app/routes/components/list.js
- toolkit/src/components/cut/list-item/types.ts
- toolkit/src/components/cut/list/pagination.hbs
- toolkit/src/components/cut/list/types.ts
The pagination component should be able to pass in all the route info the [HDS::Pagination::Compact](https://helios.hashicorp.design/components/pagination?tab=code#paginationcompact) allows. It was missing `model/models/replace`. Being able to specify the model will let us do route based pagination with this component on routes that have dynamic params based on the model. 
I also update the types of replace to `boolean` as that is what is expected and `query` to just be `unknown`
The docs update isn't related to this specific change but a change I made a while ago to set `previousPage` or `nestPage` query params when doing route based pagination. 
[CC-6362](https://hashicorp.atlassian.net/browse/CC-6362)
- :moyai: …
> CC-6362: pass route info to pagination

- .changeset/late-dots-heal.md
- documentation/tests/integration/components/filter-bar-test.js
- toolkit/src/components/cut/filter-bar/index.hbs
- toolkit/src/components/cut/filter-bar/index.ts
Updates `Cut::FilterBar` results text to show `Searching` or `Searching ${name}` if it is searching without filters. 
Brought this over to the linked branch with yalc to test it out
https://github.com/hashicorp/cloud-ui/pull/7580
> CC-5575: Update filter-bar results text for searching

- .changeset/short-avocados-bathe.md
- documentation/app/controllers/components/list.js
- documentation/app/controllers/components/service-list-item.js
- documentation/app/templates/components/service-list-item.hbs
- documentation/tests/integration/components/service-list-item-test.js
- documentation/tests/pages/service-list-item.js
- toolkit/package.json
- toolkit/src/components/cut/list-item/service/index.hbs
- toolkit/src/components/cut/list-item/types.ts
- toolkit/src/components/cut/metadata/cluster-path/index.hbs
- toolkit/src/components/cut/metadata/cluster-path/index.ts
- toolkit/src/styles/@hashicorp/consul-ui-toolkit.scss
- toolkit/src/styles/components/cluster-path.scss
Since there can be multiple services with the same name, we should also show the `cluster ID`, `partition`, and `namespace` to uniquely identify a service.
This only applies for HCP Consul and not Consul UI, so an option is added to hide the cluster path.
it does spill over if the strings are too long, but it should be fine for now? as long as the user mades it wide enough
[jira](https://hashicorp.atlassian.net/browse/CC-6361)
> CC-6361: Add cluster path to service list item

- .changeset/brave-carpets-vanish.md
- documentation/app/controllers/components/service-list-item.js
- documentation/tests/integration/components/service-list-item-test.js
- documentation/tests/pages/service-list-item.js
- toolkit/src/components/cut/list-item/section/metadata.hbs
- toolkit/src/components/cut/list-item/section/title.hbs
- toolkit/src/components/cut/list-item/service/index.hbs
- toolkit/src/components/cut/metadata/service-health-badge/index.hbs
- toolkit/src/components/cut/metadata/service-health-badge/index.ts
- toolkit/src/components/cut/text-with-icon/index.hbs
- toolkit/src/styles/components/list-item.scss
- toolkit/src/styles/components/text-with-icon.scss
A bunch of small styling updates to the list item/list-item-template:
- update cut-text-with-icon to have 12px bounding box (copied how they did this with hds-badge as you can't specify lower than 16px with flight-icon directly)
- Decrease title text size to 14px
- Decrease metadata text size to 13px
- Set rows min height to 24px
- Update health status badges to be medium not small
- Don't show any health badge if the healthchecks are empty
- Add strict mTLS icon with text
[CC-6218](https://hashicorp.atlassian.net/browse/CC-6218)
- :hourglass_flowing_sand: **[sand]**: Non-blocking, but requires future …
> CC-6218: list item template styling and strict mtls icon

- .changeset/fair-days-impress.md
- toolkit/src/components/cut/filter-bar/types.ts
There is an invalid/missing property on the FilterBar Sort type. The code expects there to be a `text` property on the sort object so that we know what to display in the toggle button, but the type definition only allows for a `value` string. 
I've also added a ticket for adopting TS in the documentation app so that we can have an easier time catching these issues earlier in development.
I brought this build over to cloud-ui in my local branch where I am re-adding sort to the services list ui. [Branch](https://github.com/hashicorp/cloud-ui/compare/CC-6566/services-list-sort)
[New issue added for adopting TS usage in the documentation app](https://hashicorp.atlassian.net/browse/CC-6583)
[WIP branch in cloud-ui](https://github.com/hashicorp/cloud-ui/compare/CC-6566/services-list-sort)
- …
> Add text property to FilterBar.Sort type

- .changeset/ten-mugs-cheat.md
- documentation/tests/integration/components/filter-bar-test.js
- toolkit/src/components/cut/filter-bar/index.hbs
- toolkit/src/components/cut/filter-bar/index.ts
AC:
- Instead of showing "Searching services" when a user inputs text in the search field update to say "Showing results for 
`<inputed search text>`"
https://github.com/hashicorp/consul-ui-toolkit/assets/23414052/36387611-5414-4856-a38e-3f84a18bff40
> CC-6624: Update FilterBar results text on search

- .changeset/grumpy-moose-smash.md
- documentation/package.json
- toolkit/package.json
- toolkit/src/styles/components/filter-bar.scss
- yarn.lock
Upgrades `@hashicorp/design-system-components` to `2.13.0`. Part of this changes the size of `Hds::Tag` I've updated the filter bar results line height to make it so that it doesn't jump around when you remove all filters due to the change in tag size. There was no token for the corresponding size.
[HDS Changelog](https://github.com/hashicorp/design-system/blob/main/packages/components/CHANGELOG.md#2130)
> Upgrade @hashicorp/design-system-components to 2.13.0

- .changeset/pink-peas-attack.md
- documentation/app/templates/components/filter-bar.hbs
- toolkit/src/components/cut/filter-bar/search.hbs
- toolkit/src/styles/components/filter-bar.scss
Allows for setting the `width` and passing `isInvalid`, `isLoading` to the `Cut::FilterBar::Search` component. I figured the other arguments from `Hds::TextInput` should be preset as they are. Still passing splattributes. through
> Update search to take width, isInvalid, isLoading

- CONTRIBUTING.md
- Makefile
- documentation/app/templates/components/service-list-item.hbs
- package.json
Now you can do a `yarn watch:toolkit` which will watch for changes in `toolkit/src` and automatically rebuild so the `documentation` app will have the latest changes.
Before, you had to run `yarn prepare` after each toolkit change.
https://github.com/hashicorp/consul-ui-toolkit/assets/23414052/8f64e7d5-e6b6-45f5-845a-e849dc48ab8f
[jira](https://hashicorp.atlassian.net/browse/CC-6659)
> CC-6659: Auto build toolkit on changes

- .changeset/metal-beds-battle.md
- toolkit/src/components/cut/copy-block/index.ts
- toolkit/src/components/cut/filter-bar/filter/checkbox.ts
- toolkit/src/components/cut/filter-bar/filter/checkmark.ts
- toolkit/src/components/cut/filter-bar/filter/index.ts
- toolkit/src/components/cut/filter-bar/filter/radio.ts
- toolkit/src/components/cut/filter-bar/index.ts
- toolkit/src/components/cut/filter-bar/sort/checkmark.ts
- toolkit/src/components/cut/list-item/index.ts
- toolkit/src/components/cut/list-item/service-instance/index.ts
- toolkit/src/components/cut/list-item/service/index.ts
- toolkit/src/components/cut/list/pagination.ts
- toolkit/src/components/cut/metadata/external-source/index.ts
- toolkit/src/components/cut/metadata/health-check-badge-set/index.ts
- toolkit/src/components/cut/metadata/service-health-badge/index.ts
- toolkit/src/components/cut/metadata/types.ts
- toolkit/src/components/cut/text-with-icon/index.ts
imports and exports of types were throwing errors on Floating Deps CI run because they were not explicitly set as type import/export.
> Fix type import error

- .changeset/config.json
Sometimes you just need to read the docs, amirite. Updates the changeset config so that releases are published as `public`. Prior to this I would have to toggle them back to public after releasing. 
Also updates the `documentation` app to be ignored so if you run `yarn changeset` you don't have to manually select the toolkit. 
[CC-6658](https://hashicorp.atlassian.net/browse/CC-6658)
[Docs](https://github.com/changesets/changesets/blob/main/docs/config-file-options.md#access-restricted--public)
- :sparkles: **[dust]**: …
> CC-6658: Update changeset config release as public

- documentation/app/templates/application.hbs
I was looking through the toolkit documentation and I noticed it was having the same sidenav refocus issue that was fixed in consul ui. I went ahead and disabled that on `HDS::SideNav`.
Here's a video demonstrating before and after. Apologies there is no audio at this time.
[video](https://github.com/hashicorp/consul-ui-toolkit/assets/5448834/841c345d-ebc4-4d81-b3f4-ce1e5b6328ed)
https://github.com/hashicorp/consul/pull/20111
> Disable a11y refocus on sidenav
